### ISSUE TITLE
Get started

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#1]
Hello @emacs-china/elpa-people!

关于是否搭建 Emacs China ELPA 镜像的投票已经结束了，结果是支持搭建：

https://emacs-china.org/t/emacs-china-elpa/217

Emacs China ELPA mirror 致力于为中国大陆用户提供稳定的、高速的各大 ELPA 镜像。

这个项目的开发已经日后的维护工作均在此 Repo 展开，@emacs-china/elpa-people 小组负责本项目，你可以根据自己的喜好自由进出该小组，如果疑问，请用一个新的 issue 提出。

Happy <kbd>M-x</kbd>ing !

**Comment by zilongshanren** [comment]
@xuchunyang 
貌似 @CodeFalling  同学已经搭好了一个 elpa mirror， 域名都绑定好了 elpa.emacs-china.org

**Comment by xuchunyang** [comment]
> 貌似 @CodeFalling 同学已经搭好了一个 elpa mirror， 域名都绑定好了 elpa.emacs-china.org

#4

**Comment by xuchunyang** [comment]
关于用什么方法搭建的问题在 #9 中讨论。
