### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#10]

**Comment by xuchunyang** [comment]
我不了解这方面的情况， @zilongshanren 你有经验，能不能介绍下相关情况？

另外，即使 HTTPS 工作了，HTTP 也必须要继续工作，因为 Emacs 要处理 HTTPS 需要更加苛刻的条件，我的 Emacs （自己编译的）目前就没法处理 HTTPS。

**Comment by zilongshanren** [comment]
@xuchunyang 
我的 spacemacs 之前开了https ， 一直下载 elpa 有问题，所以我就去掉了。

**Comment by kuangdash** [comment]
这里先看一下 dynamic-library-alist 这个变量里面的 gnutls 项，里面的库是否正确安装了？

**Comment by zilongshanren** [comment]
@xuchunyang 我这周尝试把 elpa 添加 https 的支持。

@kuangdash  我的 `dynamic-library-alist` 值是 nil，有问题吗？

**Comment by xuchunyang** [comment]
> @xuchunyang 我这周尝试把 elpa 添加 https 的支持。

+1，我昨晚试了一下，由于网络问题卡在安装 Let’s Encrypt 的客户端上了。我在自己的 VPS（境外的） 上给自己的域名加了 HTTPS，分分钟的事。

  https://certbot.eff.org/#ubuntutrusty-nginx

**Comment by kuangdash** [comment]
dynamic-library-alist 在 linux 下是 nil，在 windows 上是有内容的。

我直接套用 win 下解决 https 问题的经验了。（不过 linux 下 https 也没问题啊…）

**Comment by zilongshanren** [comment]
@xuchunyang  已添加 https 支持。

**Comment by xuchunyang** [comment]
@zilongshanren 我确认 HTTPS 能正常工作
