### ISSUE TITLE
将镜像地址加到社区顶部

### ISSUE THREAD

**Issue by li-xinyang** [emacs-china/elpa#12]
![screen shot 2016-05-10 at 11 02 40 pm](https://cloud.githubusercontent.com/assets/3349406/15151369/66b78050-1703-11e6-8264-a12a8d29dd16.png)

你们觉的勒？

**Comment by xuchunyang** [comment]
同意，但是要等到正式发布。

镜像目前应该基本可用，但是还是有一些必要的东西没完成，完成之后（预计在本周末），还需要一段测试期，要是没什么大问题的话，就会正式发布。

**Comment by qinshulei** [comment]
页面首部也加上社区本身。这样在镜像或者在社区都可以跳转。

**Comment by xuchunyang** [comment]
@li-xinyang @qinshulei 现在可以加了，谁能帮忙加下？不知道用什么图标好。

> 但是要等到正式发布。

我在网页正文注明了”测试阶段“

**Comment by xuchunyang** [comment]
也要加到 https://emacs-china.org/ 上的导航栏，并且在 https://emacs-china.org/ 上的导航栏点击 ELPA 时，不要开一个新的窗口，在同一个窗口里面打开。在 http://elpa.emacs-china.org/ 上点击 Forum 也是这样。

**Comment by xuchunyang** [comment]
Done
