### ISSUE TITLE
设计主页 http://elpa.emacs-china.org/

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#13]
谁能抽空帮忙设计下 http://elpa.emacs-china.org/ 的样式？我对网页设计一窍不通，一时半会也没什么办法。

只需要管 `gh-pages`  分支下的内容。

@li-xinyang ?

**Comment by li-xinyang** [comment]
好的呀，我可以帮忙做这个。我就干这个哒。我先设计个初稿然后搞搞？之后在这里更新。

**Comment by xuchunyang** [comment]
> 我先设计个初稿然后搞搞？之后在这里更新。

好

**Comment by li-xinyang** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/3349406/15186062/24916ef4-17ce-11e6-8d23-27567b7f0249.png)

酱子？

**Comment by xuchunyang** [comment]
好，看起来不错。“镜像地址”放到最上面好些，“安装方法”应该换成“使用方法”。

**Comment by li-xinyang** [comment]
好的，那就按照这个版本先做了后续有问题再更改。

![desktop hd](https://cloud.githubusercontent.com/assets/3349406/15186680/8564c59e-17d0-11e6-92ea-4f006214c8f0.png)

只添加样式和导航栏，其余内容均不变。

**Comment by xuchunyang** [comment]
> 只添加样式和导航栏，其余内容均不变。

为了排版方便的话，你可以去掉或者修改一些内容，等你设计好之后，我还会修改内容。总之把重点放在样式上就好了。

**Comment by li-xinyang** [comment]
http://elpa.emacs-china.org/

![1](https://cloud.githubusercontent.com/assets/3349406/15203419/31fe60c0-1836-11e6-8bff-6c26be63edcb.png)

**Comment by xuchunyang** [comment]
> 第一次给 Org-mode 导出 HTML 写样式，所有有一些限制。

Org 写中文的时候就有了问题，导致我不得不放弃了一些格式化，比如本来我想指定 `package-archives` 为代码：

> 设置 package-archives，

结果由于后面的中文逗号没法实现（在 Org-mode 内无法正确显示，导出的 HTML 也有问题）。

Markdown（至少是 Github 的 Markdown）没有这个问题。另外，Org-mode 中的链接描述如果是中文的话，在 Org-mode 内显示也有问题。要是我提前就知道这两个问题的话，就不会用 Org-mode 了。

你觉得现在换成 Markdown 怎么样？

---

> 移动自适应 iPhone 6 以下尺寸有些问题。手写的 CSS（有些乱），没有用预处语言，如果有需要之后再改。
> 
> 并没有做浏览器兼容测试，开发浏览器为最新版本 Google Chrome。
> 
> http://elpa.emacs-china.org/

在 Safari 中看起来也不错，我注意到的问题有：

- 加载的速度比较慢。那个 logo 会一点一点出现，似乎非常大。
-  Org-mode 导出 HTML 后代码块其实与 Emacs 的 Color Theme 和所用的一些 mode（比如 `rainbow-delimiters-mode`）是相关的，这样的话，对于同一个 Org-mode 文件，你的 Emacs 和我的 Emacs 导出 HTML 总会不一样。

**Comment by li-xinyang** [comment]
> 你觉得现在换成 Markdown 怎么样？

我样式是根据 org-mode 导出写的，所以换 md 似乎有些麻烦哟（要重写一部分的样式类名）。

> 加载的速度比较慢。那个 logo 会一点一点出现，似乎非常大。

中午饭前做的，Logo 是直接从 Emacs-China 论坛摘过来的，我这里没有无背景 Logo 图片在家，晚上回家换个小的（单位不能上网盘儿）。

> 你的 Emacs 和我的 Emacs 导出 HTML 总会不一样。

所以这个事情让 Travis 去做？

**Comment by qinshulei** [comment]
需要写下文档说明如何修改页面，如何导出吧。

**Comment by li-xinyang** [comment]
样式针对 Emacs 导出 HTML 写的，直接 Emacs 导出就可以了就可以使用。更新内容按照就是改 org 文件里面的文字就可以了，改完后重新导出 HTML 即可，其他文件不需要改变。

**Comment by xuchunyang** [comment]
Emacs  自动导出的 HTML 的样式不稳定，与 Org 的版本也有关系、没 `htmlize.el` 的话导出的代码块没语法高亮、Emacs Theme 不一样语法高亮的效果就也不一样。 前两个问题比较好解决：从 ELPA 安装最新的 Org 和 htmlize 应该就行了。@li-xinyang 你用的 Color Theme 是什么？

**Comment by li-xinyang** [comment]
> 你用的 Color Theme 是什么？

什么的 Color Theme？编辑器？Solarzied-dark

**Comment by xuchunyang** [comment]
就是你选用的主题，Solarzied-dark 是一个主题。就是它决定了导出的代码快的配色。

**Comment by li-xinyang** [comment]
酱紫的呀？我不知道诶。现在的颜色不好看吗？我用的白色背景，你可以换你喜欢的代码颜色主题呀。

**Comment by xuchunyang** [comment]
我觉得好看。但是现在的问题是，其他人修改的 Org 文件的话，导出的代码块的配色就会一直在变（因为每个人用的配色都不同）。

**Comment by qinshulei** [comment]
确实用org的比较难统一。不如直接html？

**Comment by xuchunyang** [comment]
导出不统一的问题，可以先放放。HTML 这个文件主要是给机器用的，不用太在意这个文件的变化。至于代码的高亮的问题，只要你自己觉得你导出的结果好看就行了，不一定要保持一致。

--

我觉得内容中部分标题居中不好看，似乎也很少见。你们怎么看？

**Comment by li-xinyang** [comment]
![1](https://cloud.githubusercontent.com/assets/3349406/15212764/403be72c-1875-11e6-855f-9649c8b838ea.png)
![2](https://cloud.githubusercontent.com/assets/3349406/15212765/40463560-1875-11e6-9e7d-fde9056fce9b.png)

标题居中还挺多的勒，随便找了两个。

**Comment by xuchunyang** [comment]
> 标题居中还挺多的勒，随便找了两个。

那现在这样就好。

Cask 那个标题看起来有些偏右，不清楚什么缘故：英文、太短了、首字母大写、我眼睛斜视。实际上是完全对齐居中了的（我量了下）。

---

等你把 Logo 修改好了，这个 issue 应该就能关掉了。

**Comment by li-xinyang** [comment]
> 等你把 Logo 修改好了，这个 issue 应该就能关掉了。

Logo 已经替换完成，有问题再 @ 我。
