### ISSUE TITLE
Watch Watching

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#14]
**UPDATE 2016/05/16**：Travis-CI 支持了 [Cron](https://docs.travis-ci.com/user/cron-jobs/)，但是使用这项功能需要申请，昨晚已申请，目前还在等回复。另外，Travis-CI 也支持用 [API](https://docs.travis-ci.com/user/triggering-builds) 触发 build，如果之前的申请未通过的话，会采取 API 的方式。总而言之，下面的问题将不复存在。

~~Watch 这个 Repo 请小心！~~

~~Emacs China ELPA 镜像的同步工作利用 Travis-CI 完成，由于 Travis-CI 的 rebuild 只能通过 commit 启动，`commit-for-travis-ci` 分支会每四个小时自动 commit 一次。因此 Watch 这个 Repo 会导致你的 Dashboard 变得非常混乱。~~

~~以后有闲置的国外 VPS 的话，也会考虑替代 Travis-CI。~~

**Comment by xuchunyang** [comment]
> Travis-CI 支持了 Cron，但是使用这项功能需要申请，昨晚已申请，目前还在等回复。

Travis-CI 回复说他们的 Cron 周期至少是一天，大家觉得把镜像同步周期改为一天怎么样？ @emacs-china/elpa-people @zilongshanren 

要是我们利用 Travis-CI 的 build API 做一个 Cron 的话，还需要一台境外的 VPS，因为 Travis-CI 的 API 的服务器（AWS）被墙了。

**Comment by zilongshanren** [comment]
@xuchunyang 
目前 elpa 4 小时更新一次采用的是什么方式？

**Comment by xuchunyang** [comment]
> 目前 elpa 4 小时更新一次采用的是什么方式？

每 4 小时 commit 一次

**Comment by zilongshanren** [comment]
@xuchunyang 这个 commit由谁触发？

**Comment by xuchunyang** [comment]
> 这个 commit由谁触发？

你的 VPS 上的一个 Cron 任务

**Comment by zilongshanren** [comment]
@xuchunyang 现在是用 travis 的 build API 无法用阿里云触发 Cron 任务了么？ 因为 AWS 被墙，所以才需要转到 Travis Cron?

**Comment by xuchunyang** [comment]
> 现在是用 travis 的 build API 无法用阿里云触发 Cron 任务了么？

是，在阿里云里没法用 travis-ci 的 api

> 因为 AWS 被墙，所以才需要转到 Travis Cron

不用 Travis Cron 的话，就还需要用一个境外的 VPS 来设置 Cron 任务

目前的三个可行的方案：

- commit（正在用，但是要淘汰掉的方案）
- Travis API （缺点是还需要一台境外的 VPS）
- Travis Cron （缺点是同步周期至少为一天）

**Comment by xuchunyang** [comment]
@emacs-china/elpa-people 
Travis 在问还需不需要给这个 Repo 开通 Cron 任务，我先把这个答应下来。明天晚上就开始用这个 Cron 任务，也就是说同步周期改成 24 小时。如果任何人觉得这个同步周期过长，造成了不便的话，随时提出。

**Comment by xuchunyang** [comment]
> Travis 在问还需不需要给这个 Repo 开通 Cron 任务，我先把这个答应下来。

好吧，Travis 是给 emacs-china 下所有的 Repo 都开启了 Cron 功能，虽然其他的 Repo 估计都用不上。

**Comment by xuchunyang** [comment]
> 因为 AWS 被墙，所以才需要转到 Travis Cron?

不全是，主要是我想省事，用 Travis Cron 只需要点击下按钮，自己用 API 再部署到 Cron 的话，相比之下，自然要麻烦些。

考虑到 24 小时更新一次还是还长了，我待会儿还是用改成 API 的方式，在我自己的 VPS 上部署相应的 Cron 任务。同步周期不变，还是 4 小时。
