### ISSUE TITLE
http://elpa.zilongshanren.com/sc/ 大小写的问题

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#15]
`sc`是小写的，但是在 vps 上面是大写的，linux是区分大小写的，应该统一一下，否则会 404.

@xuchunyang  另外，我把nginx加上了 autoindex，这样点击 elpa 链接的时候不再是 403 了，而是一个文件列表，这样看起来更像是一个镜像站点了。

**Comment by xuchunyang** [comment]
修复了，统一大写。http://elpa.emacs-china.org  上的那个链接我手写的，出现了错误。



> @xuchunyang 另外，我把nginx加上了 autoindex，这样点击 elpa 链接的时候不再是 403 了，而是一个文件列表，这样看起来更像是一个镜像站点了。

谢谢，这样不错。
