### ISSUE TITLE
镜像貌似不太稳定，有一些 package 没有爬到。。。

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#16]
另外现在 melpa 貌似是跪的。。

**Comment by xuchunyang** [comment]
有哪些 package？

> 另外现在 melpa 貌似是跪的。。

指什么？

**Comment by xuchunyang** [comment]
另外，我也是从昨天下午才开始换成这个镜像，速度很快，还没遇到什么问题。打算自己先用两天，没大问题的话，周末再邀请大家测试。

**Comment by zilongshanren** [comment]
@xuchunyang  之前用的时候 http://elpa.zilongshanren.com/melpa/ 里面是空的，现在有了。。。

**Comment by zilongshanren** [comment]
@xuchunyang  是不是在 build 的过程中，vps 上面的镜像会失效？

**Comment by xuchunyang** [comment]
> @xuchunyang 是不是在 build 的过程中，vps 上面的镜像会失效？

应该不会，同步的过程是：

- Travis-CI 下载包
- 用 rsync 上传至 VPS 上的一个临时目录（ `/var/elpa-packages/`）
- 用 rsync 同步 `/var/elpa-packages/` 至 Nginx 的服务的目录 `/var/elpa/`，这一步只会往里面添加新的内容，不会删除旧内容
- 重复上一步，但是删除掉 /var/elpa 中旧的内容

以上每一步能执行都需要前一步没有出问题。

--

用 <kbd>M-x package-install</kbd> 安装时常常会失败的原因是：Melpa 更新得非常频繁，导致用户的 archive-contents 几乎总是处于过期状态，然而 Melpa 并不会保持旧的包，因此没法安装一个久的包。我们的 Melpa 镜像没有试图解决这个问题。

**Comment by xuchunyang** [comment]
根据 Travis-CI 上 Build 日志，今天下午两点 Melpa 镜像的的确确出了问题：

https://travis-ci.org/emacs-china/elpa/jobs/129620344

第一步 Travis-CI 下载一旦失败，后续的步骤没有终止，导致 Melpa 下的文件被清空了。

**Comment by zilongshanren** [comment]
@xuchunyang  
如果 Travis 失败，应该有保护机制，或者重新开启新任务。

**Comment by xuchunyang** [comment]
相信已经修复了。
