### ISSUE TITLE
镜像构建时间间隔需要调整

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#17]
![image](https://cloud.githubusercontent.com/assets/785541/15217486/4e605b12-188e-11e6-882c-5262744cd51a.png)

 melpa构建一次要 5 个小时，我认为镜像的更新时间应该大于 5 小时，最好 6 小时更新一次，否则没有任何意义。

**Comment by zilongshanren** [comment]
@xuchunyang 现在我们是多久更新一次？

**Comment by xuchunyang** [comment]
> 现在我们是多久更新一次？

每两小时（0、2、4 ... 22）。

> melpa构建一次要 5 个小时，

melpa-stable 要 1 个小时：http://stable.melpa.org/

> 我认为镜像的更新时间应该大于 5 小时，最好 6 小时更新一次，否则没有任何意义。

可以调长一些，但是 2 个小时（理论上）也不会／应造成任何问题：假如某一次更构建没有更新任何内容，几乎什么都不会发生。

**Comment by xuchunyang** [comment]
更新周期比较短也会使得发现程序错误的机会增大。

**Comment by zilongshanren** [comment]
@xuchunyang  OK, 如果upstream 没有变化，什么也不会更新就好。我主要是担心出现上次那种情况，整个镜像无法使用，这就麻烦了。

**Comment by xuchunyang** [comment]
@zilongshanren 我把更新周期由 2 小时改为 4 小时，希望减少些给 Travis-CI 和 上游 ELPA 服务器的压力。
