### ISSUE TITLE
VPS 登陆信息

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#2]
@zilongshanren 能不能把你的 VPS 的用户名、密码和 IP 发给我？

我的邮箱：xuchunyang.me@gmail.com

其他有需要的人可以在此提出。

**Comment by zilongshanren** [comment]
@xuchunyang  你指的阿里云吗？

**Comment by xuchunyang** [comment]
应该是吧，因为你在论坛上提过你已经买了阿里云的 VPS。

**Comment by zilongshanren** [comment]
@xuchunyang  你把 ssh key 给我就行了

**Comment by zilongshanren** [comment]
@xuchunyang  guanghui8827@gmail.com

**Comment by zilongshanren** [comment]
@xuchunyang  elpa.zilongshanren.com 已经指向 阿里云的vps了。
