### ISSUE TITLE
测试阶段

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#20]
镜像进入测试阶段，该阶段结束的条件是：有一定数量用户正常地使用一段时间。

**Comment by zilongshanren** [comment]
@xuchunyang 
如何确定正在使用的用户数量？

**Comment by xuchunyang** [comment]
> 如何确定正在使用的用户数量？

我不知道，但是可以通过 unique IP 的数量推测出过去某一段时间内的用户数量。

**Comment by douglarek** [comment]
Thanks for this mirror; it looks fast enough ~ 👍

**Comment by tumashu** [comment]
Good job

**Comment by xuchunyang** [comment]
三个星期以来，一共有 41k 次下载。期间出现过一次严重的 bug #26，已经修复。

---
记一次下载的标准是：
* user-agent 中含有 URL/Emacs
* 下载的是软件包本身，而不是其他的文件

**Comment by zilongshanren** [comment]
@xuchunyang 
elpa在同步镜像的时候会把服务器上面原来的目录清空吗？还是只是 replace?

**Comment by xuchunyang** [comment]
不会清空，同步的时候，原来没有的文件直接放进去，同名的文件也会比较文件的内容，按需 replace。

**Comment by xuchunyang** [comment]
> 三个星期以来，一共有 41k 次下载

我在 http://elpa.emacs-china.org 和 GitHub READMD 上添加了一个图标：
![](https://elpa.zilongshanren.com/downloads-badge.svg)

显示的是当前的总共的下载次数，数据每天更新一次。

- 图片 https://elpa.zilongshanren.com/downloads-badge.svg
- JSON https://elpa.zilongshanren.com/downloads
