### ISSUE TITLE
Spacemacs 修改配置后安装 package 时仍然采用 elpa 原地址

### ISSUE THREAD

**Issue by tommyjiang** [emacs-china/elpa#21]
配置中加了如下语句

```lisp
(setq package-archives '(("gnu"   . "http://elpa.zilongshanren.com/gnu/")
                         ("melpa" . "http://elpa.zilongshanren.com/melpa/")
                         ("org"   . "http://elpa.zilongshanren.com/org/")))
```

但 update package 的时候仍然会从原始的网址获取，导致必须翻墙。请教如何解决，谢谢。

**Comment by xuchunyang** [comment]
在你更新之前，你能确认下 `package-archives` 的值吗？

**Comment by tommyjiang** [comment]
应该是对的，如图。

![image](https://cloud.githubusercontent.com/assets/5961425/15417811/25091eb2-1e8c-11e6-9068-fdbd67886452.png)

**Comment by xuchunyang** [comment]
> update package

具体用的是哪个命令？`M-x list-packages`？

**Comment by tommyjiang** [comment]
之前是单击的 Spacemacs Homepage 上的 Update package，我也不太清楚具体执行了什么命令。

刚才我试了下用 `list-packages` 然后手动更新是可以的，好奇怪……

**Comment by xuchunyang** [comment]
我没用过 Spacemacs，不清楚怎么回事。@zilongshanren @li-xinyang @CodeFalling 或许能解释下 ?

**Comment by zilongshanren** [comment]
@tommyjiang 
你需要在 `user-init` 里面添加下列的代码：

```elisp
(setq configuration-layer--elpa-archives
  '(("melpai-cn" . "http://elpa.zilongshanren.com/melpa/")
    ("org-cn"   . "http://elpa.zilongshanren.com/org/")
    ("gnu-cn"   . "http://elpa.zilongshanren.com/gnu/")))

```

**Comment by tommyjiang** [comment]
好的，我改下试试。

**Comment by tommyjiang** [comment]
已解决，非常感谢 @xuchunyang 和 @zilongshanren 的帮助。

**Comment by 1-riverfish** [comment]
您好，请问一下
(setq package-archives '(("gnu"   . "http://elpa.zilongshanren.com/gnu/")
                         ("melpa" . "http://elpa.zilongshanren.com/melpa/")
                         ("org"   . "http://elpa.zilongshanren.com/org/")))

这段代码应该加在哪个位置呢？
package.el的位置我没有找到....
十分感谢！！！

**Comment by 1-riverfish** [comment]
已解决，不知道什么原因，修改.spacemacs中的Init()和user-init()都没有成功更换elpa源，而修改.emacs.d/init.el文件，添加
(setq package-archives '(("gnu" . "http://elpa.zilongshanren.com/gnu/")
("melpa" . "http://elpa.zilongshanren.com/melpa/")
("org" . "http://elpa.zilongshanren.com/org/")))
成功更换源，再修改一下.spacemacs文件的dotspace-elpa-timeout为300成功解决问题
