### ISSUE TITLE
elpa.emacs-china.org 在浏览器可以访问，但是emacs提示connection time out

### ISSUE THREAD

**Issue by jiangjiechu** [emacs-china/elpa#22]

**Comment by xuchunyang** [comment]
> 但是emacs提示connection time out

怎么提示？

http://elpa.emacs-china.org/ 仅作为项目的说明主页，镜像地址并没有用 `elpa.emacs-china.org`，主页中有写每个镜像的地址。

**Comment by jiangjiechu** [comment]
首先，浏览器打开http://elpa.zilongshanren.com/elpa 是没有问题的，但是启动emacs 后，大概有10来秒的假死状态，依次显示不能进行任何操作。然后在一个新的buffer显示：
`Warning (spacemacs): 
Error connection time out for melpai-cn repository!
Warning (spacemacs): 
Error connection time out for org-cn repository!
Warning (spacemacs): 
Error connection time out for gnu-cn repository!
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package `solarized-theme-' is unavailable))
Warning (initialization): An error occurred while loading `/home/peter/.emacs.d/init.el':
`

**Comment by kuangdash** [comment]
参考 #21 ，还有 https 不是很有效可能出错

**Comment by jiangjiechu** [comment]
和#21 不太像，他的问题是archive 依然使用原来的默认地址，而我的已经是新地址了。但是仍然无法连接

**Comment by xuchunyang** [comment]
> 首先，浏览器打开http://elpa.zilongshanren.com/elpa 是没有问题的

并没有这个 URL


> 但是启动emacs 后

你是怎么配置 Emacs 来使用这个镜像的？你有看「[使用方法](https://github.com/emacs-china/elpa#使用方法)」吗？

**Comment by jiangjiechu** [comment]
已经解决。是我自己.emacs.d的问题。emacs.d缺少基本的包。
我是使用的 @zilongshanren 的spacemacs 配置，为了确保安装成功，我备份了原来的.emacs.d,然后按照他的主页给出的方法
`#clone spacemacs repo and use develop branch
git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
cd .emacs.d
git checkout --track origin/develop

#clone zilongshanren layer and checkout develop branch
git clone https://github.com/zilongshanren/spacemacs-private.git ~/.spacemacs.d/｀
他的init.el` 已经默认按照您提供的地址上的描述配置好了archive。但是emacs启动后缺一系列包，不能自动按照configuration-layer从archive安装下载。

解决方法：猜测直接从spacemacs 原始版本安装@zilongshanren 的配置缺少必要的包，于是将我原先.emacs.d/elpa/下的包拷贝到新的.emacs.d/.cache/quelpa/build下，才让安装顺利进行。
