### ISSUE TITLE
Add spacemacs usage

### ISSUE THREAD

**Issue by colin4124** [emacs-china/elpa#23]
Add below code to `dotspacemacs/user-init ()` in `.spacemacs`

> (setq configuration-layer--elpa-archives
>     '(("melpa-cn" . "http://elpa.zilongshanren.com/melpa/")
>     ("org-cn"   . "http://elpa.zilongshanren.com/org/")
>     ("gnu-cn"   . "http://elpa.zilongshanren.com/gnu/")))

Thinks for @CodeFalling

**Comment by xuchunyang** [comment]
请编辑 [README.org](https://github.com/emacs-china/elpa/blob/master/README.org) 来提交一个 PR，如果没有 Spacemacs 用户 merge 的话，我会来 merge。

（不清楚为什么 Spacemacs 不直接用 `package-archives`；而且 `configuration-layer--elpa-archives` 看起来像是个内部变量）

**Comment by xuchunyang** [comment]
See PR #25
