### ISSUE TITLE
Elpa package update error

### ISSUE THREAD

**Issue by cgoplus** [emacs-china/elpa#26]
```
package-read-archive-contents: Wrong type argument: arrayp, nil
```

**Comment by xuchunyang** [comment]
确认 Melpa 的镜像刚刚出现了问题，我重启了 Melpa 的同步，现在已经好了。

Travis CI 日志显示同步时下载的 archive-contents 文件出错了：

https://travis-ci.org/emacs-china/elpa/jobs/133689180#L244

- [ ] 出错时没有及时终止同步，还是把有问题的 archive-contents 上传上了 VPS
- [ ] archive-contents 是用 Emacs 下载的，而 Emacs 下载文件似乎不太可靠，考虑用其它工具代替
