### ISSUE TITLE
公告：支持 rsync

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#28]
如果有个人或组织也想搭建镜像的话，除了从上游 ELPA 下载这种方法之外，也可以直接 mirror 本镜像：

    rsync -rltpHS --delete-excluded rsync://elpa.zilongshanren.com/elpa/ /your/dir/

本镜像目前收录的 5 个 常见的ELPA，共占 536M

```
50M	 /elpa/gnu
63M	 /elpa/marmalade
282M /elpa/melpa
129M /elpa/melpa-stable
13M /elpa/org
```

**Comment by xuchunyang** [comment]
本镜像每天同步 3 次上游，同步开始于每天（UTC +8）的第 0，8 和 16 小时，每次同步在 30 分钟之内完成，在此期间的很短很短的一段时间内 `rsync://elpa.zilongshanren.com/elpa/` 中的内容会发生变动。

**Comment by zilongshanren** [comment]
@xuchunyang  目前 https 支持已经加上，麻烦测试一下，谢谢。

**Comment by douglarek** [comment]
@xuchunyang Tuna 同步周期是多少？

**Comment by xuchunyang** [comment]
> Tuna 同步周期是多少？

我不知道，不过我中午和刚刚分别看了下 https://mirrors.tuna.tsinghua.edu.cn/ 上 Last Update 的时间，都显示刚更新完几个小时，估计更新应该挺频繁的。

> 目前 https 支持已经加上，麻烦测试一下

Nice! 我试过了，正常工作。
