### ISSUE TITLE
Rsync access to GNU ELPA is now open.

### ISSUE THREAD

**Issue by jiegec** [emacs-china/elpa#30]
See http://lists.gnu.org/archive/html/emacs-devel/2016-07/msg00709.html.

**Comment by xuchunyang** [comment]
OK，之后我会把 GNU ELPA 的同步方式改为 rsync，至于其它的 ELPA，我也发了请求，但是我已经超过一周没打开过邮箱了，不清楚目前什么状况了。

**Comment by xuchunyang** [comment]
已经改好了
