### ISSUE TITLE
访问  elpa.zilongshanren/melpa 下面的文件，报 403 的错误

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#31]
我检查了一下这个目录下面的文件，大部分的文件权限都是正确的，但是有部分文件的权限不正确。

不清楚这个是否会影响安装，不过我目前还没有遇到不能安装的问题。

@xuchunyang  是否有必要在同步文件之后，统一给这些文件设置一个文件权限？

**Comment by zilongshanren** [comment]
https://elpa.zilongshanren.com/melpa/zoom-frm-20151231.1625.el

**Comment by zilongshanren** [comment]
![image](https://cloud.githubusercontent.com/assets/785541/16905819/ab808766-4cde-11e6-9747-53293b4ba2d1.png)

**Comment by zilongshanren** [comment]
经确认，如果访问出现 403，emacs 无法安装这个 package @xuchunyang

**Comment by xuchunyang** [comment]
这是把同步 MELPA 的方法改成 Rsync 后产生的问题，已经修复了。
