### ISSUE TITLE
以  elpa.emacs-china.org 域名来搭建 elpa 镜像

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#34]
以前的 elpa.emacs-china.org 页面改为 elpamirror.emacs-china.org

**Comment by xuchunyang** [comment]
介绍页面就用现在的 http://elpa.emacs-china.org ，Package 的地址可以用 

- `elpa.emacs-china.org/`
- 或 `elpa.emacs-china.org/packages/` （我觉得这个好些，跟其它的 ELPA 都是这种格式）

**Comment by xuchunyang** [comment]
我是嫌 elpamirror.emacs-china.org 有些长

**Comment by zilongshanren** [comment]
elpamirror.emacs-china.org 这个只是介绍页面，还好吧。之前的 elpa.zilongshanren.com 可以很容易地修改域名就可以替换成 emacs-china 的呀。

**Comment by xuchunyang** [comment]
嗯，这个介绍页面的域名也用不修改，`elpa.emacs-china.org` 的目录结构大概像这样：

```
index.html         <-- 介绍页面
packages/gnu/      <-- Packages
packages/melpa/
```

介绍页面就不用 GitHub 的 Page 服务了。

**Comment by zilongshanren** [comment]
哦 貌似也可以，后面再弄吧。我先查查论坛为何登录不了。。
