### ISSUE TITLE
制作一个介绍页面放到 elpa.emacs-china.org

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#4]
我需要一个网页介绍下 Emacs China ELPA mirror 已经它的使用方法。暂时只是一个静态页面，用 Github Page 应该就行。

**Comment by xuchunyang** [comment]
@CodeFalling 这个域名似乎被占用了？里面的内容应该可以直接拿来用。

**Comment by CodeFalling** [comment]
事实上 http://elpa.emacs-china.org/ 目前已经是一个页面了。。

**Comment by xuchunyang** [comment]
> 事实上 http://elpa.emacs-china.org/ 目前已经是一个页面了。。

我的意思是你能不能把这个页面先去掉？！究竟怎么搭建、测试、发布都还没有决定。

**Comment by CodeFalling** [comment]
Pages这边已撤销CNAME绑定，原 elpa.emacs-china.org 镜像改为  elpa.codefalling.com 留做个人使用。

修改原域名绑定 @zilongshanren

**Comment by xuchunyang** [comment]
> 修改原域名绑定 @zilongshanren

@zilongshanren 

```
$ host elpa.emacs-china.org
elpa.emacs-china.org is an alias for pages.coding.me.
pages.coding.me has address 23.91.98.188
```

**Comment by zilongshanren** [comment]
@xuchunyang 
elpa.emacs-china.org 绑定到什么？

**Comment by xuchunyang** [comment]
这个 Repo 的 Github Page

**Comment by zilongshanren** [comment]
@xuchunyang 
好的，现在就绑定

**Comment by xuchunyang** [comment]
这个页面已经制作好了：http://elpa.emacs-china.org/
