### ISSUE TITLE
ELPA 更新失败，Travis CI 无法登录服务器

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#41]
[![Build Status](https://travis-ci.org/emacs-china/elpa.svg?branch=master)](https://travis-ci.org/emacs-china/elpa)

- https://travis-ci.org/emacs-china/elpa/jobs/285538401#L594

好像是部署的 SSH 公钥被删除了。上个月也出现过同样的状况

- https://travis-ci.org/emacs-china/elpa/jobs/285538401#L596

那时我还能登录 VPS，所以就给 Travis 创建了一个新的 SSH（因为不知道怎么找回原来的公钥）。但现在我自己也不能登录了，似乎我的公钥也被删除了。

---
@zilongshanren

**Comment by zilongshanren** [comment]
@xuchunyang  把你的公钥再发我一份吧，最近我的服务器老是显示有人在美国登录，难道是travis?

**Comment by zilongshanren** [comment]
@xuchunyang 因为阿里云的云盾一直提醒我云主机在异地登录，我就修改了登录密码，并且删除了所有的ssh key。 当时没考虑elpa还在服务器上面，下次不会再出现类似错误了。。。

**Comment by xuchunyang** [comment]
> 把你的公钥再发我一份吧

https://github.com/xuchunyang.keys

> 难道是travis?

很可能

**Comment by zilongshanren** [comment]
@xuchunyang  添加了，你试试登录一下。

**Comment by xuchunyang** [comment]
我现在可以登录了。没发现原来 Travis 公钥的备份，估计明天能修复这个问题。

**Comment by xuchunyang** [comment]
已修复。
