### ISSUE TITLE
[2018-04-05] 镜像无法访问

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#46]
@zilongshanren https://elpa.emacs-china.org/ 目前无法访问，SSH 也无法登录。

**Comment by re-mx** [comment]
目前我手动测试得到的上游状态:

+ melpa.org:80 -- 正常
+ melpa.org:443 -- 正常
+ elpa.gnu.org:80 -- 无法访问
+ elpa.gnu.org:443 -- 正常
+ orgmode.org:80 -- 正常
+ orgmode.org:443 -- 正常

以上结果均与xxx(敏感词汇)无关

**Comment by zilongshanren** [comment]
@xuchunyang  重启了

**Comment by re-mx** [comment]
已经完全恢复了
