### ISSUE TITLE
同步版本有些落后

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#51]
目前 emacs-china 的 elpa 版本有些落后于 melpa.

比如 ivy， 最新的包是 11.18的，而 emacs-china上面有11.11和11.18 两个版本，我调用 `package-refresh-contents` 和  `packages-list-packages` 只能更新到 11.11版本。

切换回 melpa 正常

@xuchunyang

**Comment by xuchunyang** [comment]
我刚刚试了下没问题，刷新列表之后，<kbd>C-h P ivy</kbd> 有提醒 `20181118.1555`：

```
ivy is a dependency package.

     Status: Installed in `ivy-20181111.1757/' (unsigned).
    Version: 20181111.1757
    Summary: Incremental Vertical completYon
   Requires: emacs-24.1
Required by: swiper-20181008.1731
   Homepage: https://github.com/abo-abo/swiper
   Keywords: matching 
Other versions: 20181118.1555 (melpa), 0.10.0 (gnu).

[back]	[forward]
```

Melpa 是直接用 Rsync 同步过来的，每 4 小时同步一次，会有些延迟，内容上不太可能出问题。

**Comment by zilongshanren** [comment]
现在是可以了，我提issue的时候，更新的版本是20181111版本。可能有点延时吧。
