### ISSUE TITLE
lsp-mode 20191026.421 not found

### ISSUE THREAD

**Issue by sunng87** [emacs-china/elpa#53]
package-install-from-archive: http://elpa.emacs-china.org/melpa/lsp-mode-20191026.421.tar: Not found

感觉是同步的问题，只有这一个包存在问题

**Comment by xuchunyang** [comment]
你的缓存过期了，最新的包 lsp-mode-20191028.1838，注意 Melpa 不会保存旧版本，本 elpa 镜像自然亦如此。

**Comment by sunng87** [comment]
了解，我查了一下似乎没有办法刷新到 20191026 之后的包，是不是我们的索引没有更新了

这个目录下最新只有 20191026 的日期

https://elpa.emacs-china.org/melpa/

**Comment by xuchunyang** [comment]
哦，是我们这边的问题，服务器空间满了，我把数据放到了一个 10 GB 的分区上，结果现在空间满了。


> 本 elpa 镜像自然亦如此。

这也不对，看了下我们的 elpa 是会保存旧版本的，这也是为什么 10 GB 会不够用。

---

我用的是 https://mirrors.tuna.tsinghua.edu.cn/help/elpa/ ，不然我也会遇到同样的问题。

**Comment by xuchunyang** [comment]
我手动删了一些旧文件，腾出了一两个 G，过几个小时同步应该就 OK 了。以后再看看怎么把这个问题根除掉。

**Comment by sunng87** [comment]
已经确认修复了，感谢！
