### ISSUE TITLE
除了rsync还有其他下载镜像的方式吗

### ISSUE THREAD

**Issue by TEE-OS** [emacs-china/elpa#54]
我的网络不能使用rsync，有其他方式下载镜像的方式吗？我的http[s]可以用

**Comment by xuchunyang** [comment]
ELPA 支持 HTTP，所以任意 HTTP 客户端都行。

具体怎么操作得看你选择方法。一个思路是从 `archive-contents` 文件获得所有的包的名称，如 GNU ELPA 的 http://elpa.gnu.org/packages/archive-contents ：

```elisp
(1
 (ace-window .  ;; 包名
	     [(0 9 0) ;; 版本
	      ((avy
		(0 2 0)))
	      "Quickly switch windows." single
	      ((:keywords "window" "location")
	       (:authors
		("Oleh Krehel" . "ohwoeowho@gmail.com"))
	       (:maintainer "Oleh Krehel" . "ohwoeowho@gmail.com")
	       (:url . "https://github.com/abo-abo/ace-window"))])
...
```

然后从上面推断出下载地址 http://elpa.gnu.org/packages/ace-window-0.9.0.el ，依次类推下载所有的包，外加上前面提到的 archive-contents 基本就 OK 了。

**Comment by TEE-OS** [comment]
thanks
