### ISSUE TITLE
更换VPS

### ISSUE THREAD

**Issue by zilongshanren** [emacs-china/elpa#58]
由于我的老vps过快期了，阿里云老用户续费贵 ，我准备迁移到腾讯云，新用户很便宜，90一年。

如果换一个VPS，我需要做哪些操作？ 

@xuchunyang 

当然这个 elpa 也可以迁移到跟 emacs-china.org 同一台vps

**Comment by xuchunyang** [comment]
elpa 用 rsync 从上游下载数据，然后提供 web 服务给用户、提供 rsync 服务给下游镜像。做的工作：

- 设置 cron job 每天用 rsync 同步数据
- 设置 web 服务器
- 设置 rsyncd

elpa 这个 repo 里的代码太复杂了，有一定的历史原因（以前上游都不支持 rsync），现在没必要了，从头弄反而容易，用不着写代码。

要是你不介意，我可以来弄，https://github.com/xuchunyang.keys 这是我的 ssh public key。

**Comment by zilongshanren** [comment]
好的，需要直接把 elpa 迁移到 emacs-china.org 上吗？

**Comment by zilongshanren** [comment]
@xuchunyang 你试 ssh root@emacs-china.org， 可以把elpa迁到上面来，域名解析后面我改一下

**Comment by zilongshanren** [comment]
貌似可用空间不多了，得加一块硬盘才行。如果你要着手，请提前跟我说一下，我去加个硬盘。

**Comment by zilongshanren** [comment]
目前 emacs-china vps可用空间10G，以后备份还会增长一些，你看看够用不，如果不够，我后面再加一块20G的云盘给镜像使用。

**Comment by xuchunyang** [comment]
> 由于我的老vps过快期了，阿里云老用户续费贵 ，我准备迁移到腾讯云，新用户很便宜，90一年。

是只有 elpa 的服务器快到期了，emacs-china.org  的还没，对吧？

> 需要直接把 elpa 迁移到 emacs-china.org 上吗？这样 emacs-china.org 的东西都在一台vps上了。

不用，而且 elpa 和 论坛 这两个能分开最好了，避免相互干扰。你看能不能给 elpa 分配单独的 vps？配置最低配就够了。

> elpa.zilongshanren.com 就废弃算了。

可以继续支持，作为 elpa.emacs-china.org 的别名，指向同一个服务器上就行了。github 上搜 elpa.zilongshanren.com  有一百多个结果，应该还有些人用。

**Comment by xuchunyang** [comment]
> 目前 emacs-china vps可用空间10G，以后备份还会增长一些，你看看够用不，如果不够，我后面再加一块20G的云盘给镜像使用。

elpa 需要几个 GB，所以 10 G 是够的。

**Comment by lujun9972** [comment]
同一个域名指向多个ip可以分担流量压力吧

**Comment by zilongshanren** [comment]
这样我需要把腾讯云给你开下权限，中午弄一下

**Comment by xuchunyang** [comment]
> 同一个域名指向多个ip可以分担流量压力吧

可以，CDN 就是吧

> 这样我需要把腾讯云给你开下权限，中午弄一下

好

**Comment by zilongshanren** [comment]
@xuchunyang 好了，你可以登录 root@1.15.88.122 了，我上面也搭了一个discourse，这个你别动哈。可以先把nigix和elpa同步弄好，我后面备案迁过来了再修改域名重定向。原来的vps要9月才到期，这期间我会把一些东西全部迁移过来，包括我的个人博客。

**Comment by zilongshanren** [comment]
之前有个 git.emacs-china.org 不知道还要不要，你觉得有必要就迁过来吧。

**Comment by xuchunyang** [comment]
> 我上面也搭了一个discourse，这个你别动哈

嗯，没问题。好奇为啥要搭 discourse，http://donate.emacs-china.org/ 显示论坛的 vps 要到 2024-12-01 才到期

> 可以先把nigix和elpa同步弄好

好，我找时间弄，估计下个星期之内能弄好。

> 之前有个 git.emacs-china.org 不知道还要不要，你觉得有必要就迁过来吧。

不要了，DNS 记录可以删了。

**Comment by zilongshanren** [comment]
我另外搞的一个论坛，给游戏开发者用的

**Comment by xuchunyang** [comment]
这才发现 GNU ELPA 好像从去年底就出问题了，rsync 服务用不了，上一次同步还是在了去年底。我也是从去年底就没写过代码了，也没用 Emacs 了。

```
root@VM-0-7-ubuntu:~# rsync --list-only elpa.gnu.org::
elpa            GNU ELPA
nongnu          NonGNU ELPA
nongnu-devel    NonGNU-devel ELPA
root@VM-0-7-ubuntu:~# rsync --list-only elpa.gnu.org::elpa
@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]
root@VM-0-7-ubuntu:~#
```

而且 Melpa 的 rsync 服务也有问题，我这边一直报告连不上：

```
root@VM-0-7-ubuntu:~# rsync --list-only melpa.org::packages
@ERROR: max connections (1) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]
root@VM-0-7-ubuntu:~#
```

看样子还是从 HTTP 直接下载比较靠谱，所有的 ELPA 都支持 HTTP。这个仓库这个功能，用 Emacs Lisp 和命令行工具实现的，但是效果不好，最好重写一个。https://github.com/d12frosted/mirror-elpa 似乎可以直接用。

有没有想负责维护 Emacs China ELPA 的朋友？@Twlz0ne @cireu  @lujun9972 @LdBeth 有什么问题直接问哈

**Comment by MatthewZMD** [comment]
我有兴趣。但是人在国外，我这边建mirror对国内的没啥意义

**Comment by xuchunyang** [comment]
人在哪儿没影响，elpa 部署在现成的 vps 上，你 ssh 登陆就行，我已经把你的 public key https://github.com/MatthewZMD.keys 导入了，你可以用  `ssh root@1.15.88.122` 登录。

你可以先研究看看。这个 repo 里的代码不用管，自己从头搞，用自己喜欢的方法，有什么问题都可问我。

**Comment by seagle0128** [comment]
如果需要人力，可以算我一个，可以抽空帮忙维护。

**Comment by xuchunyang** [comment]
确实需要帮助，我的兴趣、时间和能力都不太够，本来是很简单的事情，我弄以来一直很吃力，耗时间来回折腾，效果也不好。所以从头再弄。有条件的朋友可以把这事接手过去。

**Comment by MatthewZMD** [comment]
> 人在哪儿没影响，elpa 部署在现成的 vps 上，你 ssh 登陆就行，我已经把你的 public key https://github.com/MatthewZMD.keys 导入了，你可以用 `ssh root@1.15.88.122` 登录。
> 
> 你可以先研究看看。这个 repo 里的代码不用管，自己从头搞，用自己喜欢的方法，有什么问题都可问我。

成功登陆了。只是我也没有搞这个的经验，需要花点时间研究研究。也可以加上 @seagle0128 一起研究

**Comment by seagle0128** [comment]
现在需要我做什么？晚上我可以看看

**Comment by xuchunyang** [comment]
先把 elpa 镜像搭起来

**Comment by zilongshanren** [comment]
现在elpa情况怎么样了？ @xuchunyang @seagle0128

**Comment by xuchunyang** [comment]
没进展。

我想乘这个机会交把 elpa 交给其它人做，由于我很久不用 Emacs 了，热情少了。

我在想办法，一是直接把旧的迁移过来；二是重新弄下，我本周内再报告进展。

**Comment by Claude-Ray** [comment]
现在 http://elpa.emacs-china.org/melpa/ 访问提示 403，和上面的调整相关吗？

**Comment by xuchunyang** [comment]
不是，我没记错的话，应该就是故意弄成 403 的（原来是列出所有的包的，但是发现包数量太多，页面太大，下载太慢）

**Comment by xuchunyang** [comment]
现在想想可以起码写个说明要好些。

**Comment by xuchunyang** [comment]
我打算直接用 https://github.com/d12frosted/elpa-mirror 的，里面有现成的文件，但是国内网络访问 GitHub 有问题

```console
root@VM-0-7-ubuntu:/tmp# git clone --depth 1 --verbose https://github.com/d12frosted/elpa-mirror.git
Cloning into 'elpa-mirror'...
fatal: unable to access 'https://github.com/d12frosted/elpa-mirror.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
```

所以想把这个 repo 弄个 gitee 镜像，https://github.com/xuchunyang/gitee-mirror ，折腾了2小时，也没搞定。

**Comment by cireu** [comment]
我现在主要是用GNU Guix的Emacs包加上自己git submodule,也基本不用ELPA了

**Comment by zilongshanren** [comment]
@xuchunyang 周末我试试  https://github.com/d12frosted/elpa-mirror

**Comment by xuchunyang** [comment]
@zilongshanren https://github.com/Yikun/hub-mirror-action 这个我原本打算试试得，自动把 github repo 同步到 gitee

**Comment by LdBeth** [comment]
https://github.com/LdBeth.keys

也请加一下我的 pub key，有空应该可以整下。

**Comment by xuchunyang** [comment]
@LdBeth 已加

**Comment by LdBeth** [comment]
```
ldbeth@mab:~$ rsync rsync://elpa.gnu.org/elpa/
@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]
ldbeth@mab:~$ rsync rsync://melpa.org/packages/
@ERROR: max connections (1) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]
```
我用在加州的服务器也连不上，看来上游 rsync 都挂了

**Comment by xuchunyang** [comment]
> 我用在加州的服务器也连不上，看来上游 rsync 都挂了

是的，gnu 的去年底就挂了。

**Comment by xuchunyang** [comment]
今晚我有在重写，不清楚能不能弄好，即便弄好了，日后维护还需要人，最好是 Emacs 用户，而我已经半年没用 Emacs 了。

**Comment by LdBeth** [comment]
我倒是一直在用，不过更新包的頻率只有一二个月一次。己经先把这 repo clone 到 VPS 上了。

**Comment by xuchunyang** [comment]
@zilongshanren 内容同步了，文件放在 /root/elpa-mirror-2021-main ，HTTP 服务放 http://1.15.88.122/ ，可以把 elpa.emacs-china 的 DNS 改到这个 IP，然后我在设置 HTTPS 和 rsync 服务。

```el
(setq package-archives
      '(("gnu" . "http://1.15.88.122/gnu/")
        ("melpa" . "http://1.15.88.122/melpa/")))
```

**Comment by xuchunyang** [comment]
@LdBeth 等 @zilongshanren DNS 改好了，有空的话，可以帮忙设置下 HTTP 服务器，加下 HTTPS 证书。我有个 Tmux session 跑着 Caddy 服务器，你用 `tmux attach` 上去关了。

**Comment by LdBeth** [comment]
试着配置了下 https，还没搞定。Caddy server 已经关了。

**Comment by LdBeth** [comment]
我设置了下 http，让 caddy 在后台跑了，这样有的用户可以用 ip 就急一下。

**Comment by xuchunyang** [comment]
@LdBeth 那个 DNS 还没改过来，没法配置 HTTPS。

```console
➜  ~ host elpa.emacs-china.org
elpa.emacs-china.org has address 112.124.58.18
```

**Comment by xuchunyang** [comment]
还有 rsync 服务也要开下，给下游做镜像，我还没有开。

**Comment by LdBeth** [comment]
我把 rsync 挂 systemd 上了。我 config 这样写的，应该没问题

```
max connections = 4
uid = nobody
gid = nobody
log file = /var/log/rsync.log
timeout = 500

[elpa]
	include = gnu melpa melpa-stable org user42
	path = /root/elpa-mirror-2021-main
```

**Comment by BlindingDark** [comment]
可以的话我也帮下忙 https://github.com/BlindingDark.keys

现在同步的方案是拉 d12frosted/elpa-mirror 这个仓库，还是走 HTTP 直接拉上游？

**Comment by LdBeth** [comment]
@BlindingDark 加好了。

現在是手动下載 elpa-mirror 仓库，VPS 连不上 github，还要想辦法。

**Comment by BlindingDark** [comment]
👌我试试搞搞 gitee 同步

d12frosted/elpa-mirror 大概有 5.6G。

Gitee/Coding 官网说法是仓库大小限制 500M，实际好像是 1G。如果向 gitee/coding 申请自动镜像同步的话到是可以，问题是 1. 这个仓库不是官方仓库 2. 全交给他们同步，我们能控制的内容非常少，比如同步的频率。

所以没有直接用 HTTP 同步的原因是什么？也是因为网络速度问题么？

@xuchunyang @LdBeth

**Comment by BlindingDark** [comment]
看了下，拉不下来的原因是 git 设置了 http.proxy，这个 proxy 应该是出问题了，因为我拉 gitee 的 repo 也报一样的错。

我尝试使用 gitlab 上的 elpa-mirror，速度可以到 10MiB/s（github 依然龟速）
![image](https://user-images.githubusercontent.com/13600799/114668114-ede3ff80-9d32-11eb-9f10-9d9d5a75ad59.png)

**Comment by xuchunyang** [comment]
@LdBeth rsync 怎么用的，列出来文件内容？

```console
➜  ~ rsync --list-only rsync://1.15.88.122
elpa
➜  ~ rsync --list-only rsync://1.15.88.122/elpa
@ERROR: invalid gid nobody
rsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]

➜  ~ rsync --list-only rsync://mirrors.tuna.tsinghua.edu.cn/elpa/
drwxr-xr-x             12 2020/11/23 15:52:15 .
drwxrwxr-x             23 2016/11/25 11:43:48 SC
drwxr-xr-x          2,318 2021/04/06 11:37:13 emacswiki
drwxr-xr-x          4,588 2020/12/25 06:05:02 gnu
drwxrwxr-x          1,164 2019/12/04 08:07:35 marmalade
drwxr-xr-x         15,269 2021/04/09 16:44:59 melpa-stable
drwxr-xr-x         24,518 2021/04/09 13:51:00 melpa
drwxrwxr-x             13 2021/04/06 20:06:50 nongnu
drwxrwxr-x              5 2021/04/06 20:06:50 org
drwxrwxr-x             23 2018/04/04 16:06:35 sunrise-commander
drwxrwxr-x            185 2021/04/07 00:07:15 user42
```

**Comment by LdBeth** [comment]
> 所以没有直接用 HTTP 同步的原因是什么？也是因为网络速度问题么？

因为同步脚本还在写。具体细节

> rsync 怎么用的，列出来文件内容？

我多设了 `gid`，看来要取消。实际上这里不应该用 root 而是专门搞个用户去同步。网页的结构也要整理一下。

目前己经可以了

```
>> 0:~ $ rsync --list-only rsync://1.15.88.122/elpa                                                          << 17:12 <]
drwxr-xr-x        4096 2021/04/14 13:01:14 .
-rw-r--r--       12288 2021/04/14 12:39:21 .Caddyfile.swp
-rw-r--r--          45 2021/04/14 00:22:09 .gitignore
-rw-r--r--         105 2021/04/14 12:13:23 Caddyfile
-rw-r--r--          19 2021/04/14 00:22:09 README.md
-rw-r--r--         653 2021/04/14 07:51:34 archive-contents-to-json.el
-rw-r--r--        2086 2021/04/14 12:59:03 config.json
-rw-r--r--         468 2021/04/14 13:01:14 index.html
-rw-r--r--        3138 2021/04/14 08:43:31 index.js
-rw-r--r--         324 2021/04/14 12:43:10 index.md
-rw-r--r--        1217 2021/04/14 00:22:09 package-lock.json
-rw-r--r--         605 2021/04/14 00:22:09 package.json
drwxr-xr-x       16384 2021/04/14 08:40:25 gnu
drwxr-xr-x      118784 2021/04/14 08:40:29 melpa-stable
drwxr-xr-x      282624 2021/04/14 08:40:27 melpa
drwxr-xr-x        4096 2021/04/14 00:31:37 node_modules
drwxr-xr-x        4096 2021/04/14 08:40:30 org
drwxr-xr-x        4096 2021/04/14 08:41:51 user42
```

**Comment by xuchunyang** [comment]
> 所以没有直接用 HTTP 同步的原因是什么？也是因为网络速度问题么？

能用 rsync 的话，优先使用，但是 rsync 服务都有问题：

- gnu elpa 的坏了
- melpa 的国内连不上，或者太卡
- 其它 elpa 如 org 没有 rsync

不优先用 HTTP 是怕干扰，比如 melpa 有个统计下载数量，做镜像会造成影响，可以使用 melpa 官方的镜像（如果这个镜像没问题的话，我听说 melpa stable 的镜像好像有问题），如果用官方的，看看用不用跟上游沟通，看看能不能解决干扰问题。

目前同步，可以统一都用 HTTP，我昨晚写的同步代码也是用 HTTP。

**Comment by BlindingDark** [comment]
所以同步的代码是决定自己写了么？https://github.com/dochang/elpa-clone 是 elpa-mirror 用的，如果是打算从头写我就不在这个基础上修补了。

**Comment by zilongshanren** [comment]
> @zilongshanren 内容同步了，文件放在 /root/elpa-mirror-2021-main ，HTTP 服务放 http://1.15.88.122/ ，可以把 elpa.emacs-china 的 DNS 改到这个 IP，然后我在设置 HTTPS 和 rsync 服务。
> 
> ```emacs-lisp
> (setq package-archives
>       '(("gnu" . "http://1.15.88.122/gnu/")
>         ("melpa" . "http://1.15.88.122/melpa/")))
> ```

等我5.1回湖南把备案迁移过来了再指定域名吧，现在指向过来怕被封。

**Comment by xuchunyang** [comment]
@LdBeth 好的。rsync --list-only 还能显示一些自定义信息，比如可以显示整个镜像的大小，以后可以加上。

**Comment by xuchunyang** [comment]
@zilongshanren 那有人先把现在的修复了吗？我还没看怎么就不能访问了

**Comment by xuchunyang** [comment]
> 所以同步的代码是决定自己写了么？https://github.com/dochang/elpa-clone 是 elpa-mirror 用的，如果是打算从头写我就不在这个基础上修补了。

可以自己写，也可以用别人的，关键是后面维护的事情。

**Comment by zilongshanren** [comment]
> @zilongshanren 那有人先把现在的修复了吗？我还没看怎么就不能访问了

现在的一直没动呀，现在是什么问题？服务器要9月才过期呢

**Comment by zilongshanren** [comment]
> @zilongshanren 那有人先把现在的修复了吗？我还没看怎么就不能访问了

我晕，我自己也访问不了了，感觉被黑客黑了。。我上去看看怎么回事

**Comment by xuchunyang** [comment]
@zilongshanren 论坛上反映 https://elpa.emacs-china.org/gnu/ 打不开，我当时也试了，确实有问题，但是现在又试了一次，又好了，但有时候很卡。

https://emacs-china.org/t/elpa/16965

我的 `ssh root@elpa.emacs-china.org` 连不上了，同步的代码也失效了，elpa 很久没更新了。

@zilongshanren 看看能不能加下 @LdBeth 的 ssh key 到 elpa.emacs-china.org ，想办法把现在的 elpa 更新下

**Comment by zilongshanren** [comment]
> @zilongshanren 论坛上反映 https://elpa.emacs-china.org/gnu/ 打不开，我当时也试了，确实有问题，但是现在又试了一次，又好了，但有时候很卡。
> 
> https://emacs-china.org/t/elpa/16965
> 
> 我的 `ssh root@elpa.emacs-china.org` 连不上了，同步的代码也失效了，elpa 很久没更新了。
> 
> @zilongshanren 看看能不能加下 @LdBeth 的 ssh key 到 elpa.emacs-china.org ，想办法把现在的 elpa 更新下

我刚刚重启了一下主机，貌似好了，之前cpu占用特别高，不知道什么原因。
我把他的key加一下

**Comment by zilongshanren** [comment]
> https://github.com/LdBeth.keys
> 
> 也请加一下我的 pub key，有空应该可以整下。

你试试 ssh root@elpa.emacs-china.org， 现在加上你了

**Comment by LdBeth** [comment]
> 你试试 ssh root@elpa.emacs-china.org， 现在加上你了

能上去了

**Comment by xuchunyang** [comment]
前几天的确有问题，我有 uptimerobot 监控，提示有 50 小时连不上。

@LdBeth 以后同步方案搞好了，再弄个状态检测的功能，啥时候同步的，同步了啥，网站状态、rsync 状态，下载量等数据都采集。还有网页也可以重新设计下，比如加一个搜索包的功能。

**Comment by LdBeth** [comment]
我先把 1.15.88.122 的东西同步到 elpa.emacs-china.org 上。

**Comment by xuchunyang** [comment]
@LdBeth 好的，elpa.emacs-china.org 用的是 nginx

**Comment by BlindingDark** [comment]
https://gitee.com/blindingdark/elpa-clone

给 elpa-clone 写了 systemd 定时任务，目前是用 HTTP 直接从源头拉的，改的话直接改这里的脚本 https://gitee.com/blindingdark/elpa-clone/blob/master/elpa-clone.sh#L51

在新的同步做好之前可以先用这个

**Comment by LdBeth** [comment]
问一下，理论上是不是就算用 HTTP 也可以通过分析 `archive-contents` 只下載更新了的包？

**Comment by xuchunyang** [comment]
@LdBeth 嗯，从 archive-contents 得到文件名就行了，本地已有的就无需在下载了

https://github.com/xuchunyang/elpa-mirror-2021/blob/main/archive-contents-to-json.el 我昨晚写的把 archive-contents 弄成 json

**Comment by LdBeth** [comment]
我打算用 Chez Scheme 写同步工具，` archive-contents` 刚好也可以当做 Scheme 文件直接读。这样就不用调用 Emacs 了。

**Comment by BlindingDark** [comment]
> 问一下，理论上是不是就算用 HTTP 也可以通过分析 `archive-contents` 只下載更新了的包？

elpa-clone 里面是这么做的，读 archive-contents 之后调用 `cl-set-difference`，可以参考一下
https://gitee.com/blindingdark/elpa-clone/blob/master/elpa-clone.el#L230

**Comment by LdBeth** [comment]
我已经把同步脚本写好了，測试以后应该就可以用了

**Comment by xuchunyang** [comment]
> 我先把 1.15.88.122 的东西同步到 elpa.emacs-china.org 上。

gelpa 的还没更新是吧？gnu/archive-contents 还是去年底的

```
➜  ~ rsync --list-only rsync://elpa.emacs-china.org/elpa/gnu/archive-contents
-rw-r--r--         85,336 2020/12/25 06:02:14 archive-contents

➜  ~ curl -I http://elpa.emacs-china.org/gnu/archive-contents
HTTP/1.1 200 OK
Server: nginx/1.10.1
Date: Thu, 15 Apr 2021 04:11:29 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 85336
Last-Modified: Thu, 24 Dec 2020 22:02:14 GMT
Connection: keep-alive
ETag: "5fe50fe6-14d58"
Accept-Ranges: bytes
```

**Comment by LdBeth** [comment]
我忘了，现在同步好了。

**Comment by LdBeth** [comment]
试了下同步脚本应該没问題了，有谁能帮把这个写成 systemd service 吗？

https://github.com/LdBeth/sync-elpa

**Comment by xuchunyang** [comment]
定期同步任务现在用的是 cronjob。

**Comment by BlindingDark** [comment]
@LdBeth 

运行方式是这么运行的么？
```shell
/root/sync-elpa /var/log/sync-elpa.log
```

---

`/usr/lib/systemd/system/sync-elpa.service`

```ini
[Unit]
Description=Sync ELPA archive
After=network.target

[Service]
ExecStart=/bin/bash -c "/root/sync-elpa /var/log/sync-elpa.log"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

`/usr/lib/systemd/system/sync-elpa.timer`

```ini
[Unit]
Description=Runs sync-elpa every 6 hours

[Timer]
OnUnitActiveSec=6h
Unit=sync-elpa.service

[Install]
WantedBy=multi-user.target
```

```shell
systemctl daemon-reload
systemctl enable sync-elpa.timer
```

**Comment by LdBeth** [comment]
@BlindingDark 

> 运行方式是这么运行的么？

Chez 生成 executable 有點麻煩，用法现在是 `/usr/bin/scheme-script /root/sync-elpa/out /var/log/sync-elpa.log`。

> ExecStart=/bin/bash -c "/root/sync-elpa /var/log/sync-elpa.log"

这行可以把 bash 換掉吗？

**Comment by BlindingDark** [comment]
> 这行可以把 bash 換掉吗？

可以。

**Comment by LdBeth** [comment]
@xuchunyang 原来的 VPS 的 apt 里没有 Chez Scheme，是要更新还是得自个装？编译一下倒也不麻烦。

**Comment by BlindingDark** [comment]
其实 systemd 更常见的做法是直接把日志打到 stdout，这样就交给 systemd 的日志系统来处理了（就是可以用 journalctl 操作）。

**Comment by xuchunyang** [comment]
@LdBeth 我不清楚，没用过 Chez

**Comment by LdBeth** [comment]
> 其实 systemd 更常见的做法是直接把日志打到 stdout

那我改下。

**Comment by LdBeth** [comment]
我先把这个更新脚本挂新的 VPS 上去了。旧的就从那里 rsync 好了。

**Comment by LdBeth** [comment]
```
(define elpa-alist
  '(["gnu/" . "http://elpa.gnu.org/packages/"]
    ["melpa/" . "https://melpa.org/packages/"]
    ["melpa-stable/". "https://stable.melpa.org/packages/"]))
```
目前这个只更新了这三个源。有其它要加的吗？

**Comment by xuchunyang** [comment]
还有 orgmode 的，其它的看你的想法，可加也可不加，不常用，non-gnu, user42, sc 。还有个 Marmalade 就不加了吧，早就不更新了。sc 我也没用过，不清楚有没有必要。non-gnu 刚出的。user42 我也不用，但是貌似作者比较靠谱，而且个人 elpa 很少，我觉得支持下比较好，反正也不麻烦。

**Comment by xuchunyang** [comment]
同步的时候，可以加个中间步骤，避免同步中间用户访问。假设没有中间步骤，再假设你先同步了 archive-contents 文件，此时用户使用，由于其它文件还没来得及同步，用户可能会遇到 404 问题。不加的话中间步骤的话，可以把 archive-contents 最后同步，旧的文件就不用删除。

**Comment by LdBeth** [comment]
> 同步的时候，可以加个中间步骤

我是先用 curl 取得 `archive-contents`，生成更新列表以后用输出给 parallel 并行下載，最后再更新 archive-contents (而且还是先下到一个 tmpfile，下完再 rename)。更新完再把不要的文件删了。

不过我没做足够的异常处理，这个同步工具假设每个包只有一个版本。目前计划再写个检查 `archive-contents` 和目錄內容一致性的检查。

**Comment by xuchunyang** [comment]
还有，如果用中间目录的话，别人用 rsync 同步的时候也不容易出问题。

**Comment by LdBeth** [comment]
@xuchunyang 有没有人向 gnu elpa/melpa 提过他們 rsync 的问题？如果能解决那最好。

---

順带 melpa 的 rsync 似乎已经可以用了

**Comment by LdBeth** [comment]
<img width="836" alt="螢幕快照 2021-04-15 下午10 19 33" src="https://user-images.githubusercontent.com/22933696/114884821-a9db2280-9e38-11eb-81e8-f97501bce898.png">

最好直接在原来的 VPS 上把 melpa 的 rsync 设好。

**Comment by xuchunyang** [comment]
melpa 的 rsync 一直可用，但是貌似很卡，且有时连不上（rsync 服务同时连接有数量限制），现在 melpa 就是用 rsync 同步的。

gnu elpa 的，我没有沟通，我不晓得上游知不知道。你可以反馈下。 gnu 和 melpa 的 rsync 服务都是我建议后才加上的。orgmode 的我也说过，但没人理我。

**Comment by xuchunyang** [comment]
> 现在 melpa 就是用 rsync 同步的。

你看下 cronjob，`cron -l`

**Comment by LdBeth** [comment]
@xuchunyang `cron` 出问題了

<img width="679" alt="螢幕快照 2021-04-15 下午11 02 31" src="https://user-images.githubusercontent.com/22933696/114891684-ab0f4e00-9e3e-11eb-85d1-754571e45959.png">

**Comment by LdBeth** [comment]
嗯，Melpa 是在正常同步，是 gnu 出了问題。

---
```
root@AY1309092152572985dfZ:/var/log# ls -lh rsync-*.log
-rw-r--r-- 1 root root  96M Apr 15 20:05 rsync-gnu-elpa.log
-rw-r--r-- 1 root root 2.0G Apr 15 20:47 rsync-melpa.log
-rw-r--r-- 1 root root 903M Apr 15 20:45 rsync-melpa-stable.log
```

这不清理真的没问題吗？

**Comment by LdBeth** [comment]
我向 gnu elpa 提了个 bug，[47803](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=47803)。

**Comment by xuchunyang** [comment]
> 我忘了，现在同步好了。

HTTP 的好了，但是 Rsync 的还没有

```console
➜  web-frontend-exercise git:(main) ✗ rsync --list-only rsync://elpa.emacs-china.org/elpa/gnu/archive-contents
-rw-r--r--         85,336 2020/12/25 06:02:14 archive-contents
```

**Comment by LdBeth** [comment]
> The problem was introduced when we moved things around for the
introduction of the NonGNU archive.
>
> I believe I have fixed it, so you can now use rsync://elpa.gnu.org/elpa
again, and more generally rsync://elpa.gnu.org/{elpa,nongnu}{,-devel}
>
> Thanks for telling us about it,
>
>
>        Stefan

GNU ELPA 的 Rsync 現在好了。

> HTTP 的好了，但是 Rsync 的还没有

crontab 自动同步好了。

```
$ rsync --list-only rsync://elpa.emacs-china.org/elpa/gnu/archive-contents
-rw-r--r--       89776 2021/04/19 05:03:13 archive-contents
```

**Comment by LdBeth** [comment]
@xuchunyang 我是不是可以先让临时镜像 offline 了？

**Comment by xuchunyang** [comment]
@LdBeth 可以

**Comment by xuchunyang** [comment]
https://elpa.emacs-china.org/ 这个网站的内容过时了，可日后再改：

- last update 的 badge 我以前弄得有问题，好像不能反映更新成功了没有
- 把 Marmalade 去掉，上游早就不维护了
- 网页中提到 rsync “整个镜像约占 1 GB” 这个信息不对，不反映真实情况

还有 rsyncd 配置里的信息也过时了，之前是我写死了的：
```
➜  ~ rsync --list-only rsync://elpa.emacs-china.org

elpa            Emacs China ELPA mirror contents (approx 536M on 2016-06-02)
```

- http://elpa.emacs-china.org/melpa/ 返回 403，是故意如此，因为某些原因（如目录文件太多，导致 nginx 生成的 index.html 太大，太慢）。但是这样用户体验不好，遇到 403 的话，会以为镜像有问题。Caddy 的 http://1.15.88.122/melpa/ 感觉好些，我不清楚是不是服务器差别。总之就是这个页面不应该 403。

**Comment by LdBeth** [comment]
> 把 Marmalade 去掉，上游早就不维护了

> Marmalade endeavours to deliver stable releases. This means some packages are considered stale. The repository has had availability problems and is now managed by NicFerrier who says he is slowly fixing things. A recent edit to this page incorrectly identified the project as discontinued; however. as of a 2020-10-31 twitter conversation Nik is still interested in learning of new outages/breakage. Issues are tracked on the project’s github repository.

不急着去掉，不过好像那几个 repo 都没设过同步？

我先把 rsync size 更新一下。

**Comment by xuchunyang** [comment]
> 不急着去掉

好。有的文件还可以留着，但是网页[1]上不写（或者说清楚），对于上游已经废弃的 elpa，就不让用户以为还是正常的，可以使用。

[1] 网页指的是 elpa 镜像的说明，http://elpa.emacs-china.org/ 还有这个项目的 README，这个事情以后再说，等你把镜像弄完了再改也不迟。

> 不过好像那几个 repo 都没设过同步？

marmalade 不知道什么时候我决定不同步了，应该是上游有问题的时候。sunrise-commander 从 2018 年起就不更新了，上游连不上，可以去掉（【去掉】不一定就要删除文件，也可保留文件，但是不再更新）

> 我先把 rsync size 更新一下。

好的。可以 a）去掉，不写大小，这样也行；b）写死大写，比如 1 GB。总之不好弄就不弄了，不是重要的事情。

---

还有一个问题是 melpa 删除旧文件的问题，而 gelpa 不删除旧文件，这里说的如果你从它们的 rsync 同步的话。

melpa 因为包多且更新多，选择不保留。虽然我觉得没必要把旧文件删了，硬盘空间应该很便宜才是。而 gelpa 包少，而且更重要的是，为了完整性，包（就像所有的网页一样）不应该随随便便删掉。你自己维护镜像，也遇到了这个选择。

**Comment by LdBeth** [comment]
@zilongshanren elpa.emacs-china.org 服务器又掉线了，ssh 连不上，麻烦看一下是啥情况。

**Comment by zilongshanren** [comment]
> @zilongshanren elpa.emacs-china.org 服务器又掉线了，ssh 连不上，麻烦看一下是啥情况。

大概率又是资源耗尽，准备重启试下。重启后好了。。

**Comment by zilongshanren** [comment]
域名备案陷入死循环了，我的身份证换了广东的，要备案必须先更改备案人信息。而湖南的备案不让改到广东，导致我只能继续使用阿里云了。。。 腾讯云只能用来干点别的了。。。域名都迁不过去，我醉了。

**Comment by zilongshanren** [comment]
最近更新： 已经提交管局审核，坐等通过了。

**Comment by zilongshanren** [comment]
@LdBeth 现在同步melpa要怎么操作，腾讯云备案通过了，可以开整了。

**Comment by zilongshanren** [comment]
@xuchunyang 新的机器备案已经弄好了，域名重定向也改了，啥时候有空弄一下吧？或者写个readme，我来弄也行。

**Comment by xuchunyang** [comment]
@LdBeth 有时间看下吗？腾讯云 VPS 上的 ELPA 同步怎么样了，能用吗？

**Comment by zilongshanren** [comment]
或者我简单的用  https://github.com/d12frosted/elpa-mirror 这个仓库就行了？

**Comment by xuchunyang** [comment]
可以

**Comment by LdBeth** [comment]
我准备还是照着原来的来，能直接从上游 rsync 就 rsync，没有 rsync 的我在重写可以做读取服务器自动生成的`index.html`的同步工具。老服务器的內容已经同步过去了。

**Comment by xuchunyang** [comment]
那等你弄好了，让 @zilongshanren 改下 DNS 记录就好了。

**Comment by zilongshanren** [comment]
目前改好了，直接使用 https://github.com/d12frosted/elpa-mirror 这个镜像了
