### ISSUE TITLE
统计下载数据

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#6]
记录包括下载信息，以备日后使用。现在能想到应用包括：

- 每个包的下载量
- Emacs 的版本信息。等到 Emacs 25 之后，我们就能统计出用户使用 Emacs 的版本情况了。

**Comment by CodeFalling** [comment]
这也就是目前方案的主要缺点了，没有办法统计具体的下载量。

> Emacs 的版本信息。等到 Emacs 25 之后，我们就能统计出用户使用 Emacs 的版本情况了。

`package.el` 在下载 packages 会携带具体的 emacs 版本信息么？

**Comment by xuchunyang** [comment]
> package.el 在下载 packages 会携带具体的 emacs 版本信息么？

Emacs 25 （还没发布）应该会，从 trunk 安装的话默认应该已经包含了，比如我的 Emacs 所用的 user-agent：

```
(url-http-user-agent-string)
    ⇒ "User-Agent: URL/Emacs Emacs/25.1.50.4 (nil; nil)
"
```

**Comment by xuchunyang** [comment]
所需要的数据都能在 Nginx 的日志中得出，下面时一个示例（是我的 Emacs 安装了 magit 时所产生的）：

    221.231.81.216 - - [13/May/2016:12:20:15 +0800] "GET /melpa/magit-20160512.1510.tar HTTP/1.1" 200 1157120 "-" "URL/Emacs Emacs/25.1.50.7 (OpenStep; x86_64-apple-darwin15.4.0)"
