### ISSUE TITLE
用什么方法搭建 ？

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/elpa#9]
考虑到 @CodeFalling 似乎已经搭建好了一个镜像，现在有必要讨论下如何搭建了。

我的方案是用直接用一个国内 VPS 托管包文件，如果有必要，现在一台境外 VPS 下载好同步回国内的 VPS。

这么做的优点是：

- 完全独立，不完全依附任何商家，从而使得稳定性和速度在我们的控制之中。
- 使用单独的服务器能记录各种统计数据 #6

缺点是：

- 不能用 emacs-china.org 这个域名（我不是太介意这个问题。因为这不是我们所能控制的，假如这造成了不方便的话，我也希望把这不方便传递给每一个使用该镜像站的用户）

@CodeFalling 你能不能也介绍下你的方案？

**Comment by CodeFalling** [comment]
我的方案是使用 Travis-CI 定时爬 packages 并且托管在 CodingNet Pages。

优点：
- 现在就已经可用了，可以在 http://elpa.emacs-china.org/ 访问到

- 整个过程完全不需要维护成本，不需要人工参与且无费用，这意味着其可以长期稳定的运行下去且无任何负担

- CodingNet 在国内的访问速度还不错，而且不需要备案，可以直接使用  emacs-china 的域名

- 我认为商家的稳定性和速度完全在我们之上

- 过来更换方案时较为平缓，使用方法不会发生改变

缺点：

- 没有什么好的统计方案

- 不支持 https，虽然可以通过 CDN 实现，但是会丧失速度优势

- CodingNet 可能会停止服务-。-如果国内类似的公司都停止服务了我们就只能更换到 VPS

总体来说我认为可以将这个方案作为备案成功前的过渡方案，因为从头到尾域名不需要变动，用户的使用方法都不会改变

> 因为这不是我们所能控制的，假如这造成了不方便的话，我也希望把这不方便传递给每一个使用该镜像站的用户

。。这句话是打错了么

**Comment by xuchunyang** [comment]
> 整个过程完全不需要维护成本，不需要人工参与且无费用，这意味着其可以长期稳定的运行下去且无任何负担

不需要成本是指成本转移给 Travis-CI 和 CodingNet 吧，不确定你这么做会不会超出“合理使用”的范畴。有这种好事的话，各个大学都用不着用自己学校的服务器搭建镜像站了。

> CodingNet 在国内的访问速度还不错，而且不需要备案，可以直接使用 emacs-china 的域名

不了解 CodingNet 的速度，这个速度我们也无法控制，实际上我们可能都不能准确地知道速度决定是怎样的。


> 。。这句话是打错了么

我的意思是“域名未备案就不能用”这件事不是我们所能控制的，只要跟用户讲清楚了，也不是非要用 emacs-china.org 这个域名。

**Comment by CodeFalling** [comment]
诸如 Ubuntu 镜像等是根本不可能被塞进一个 repo 里的。。事实上 CodingNet **自身就确实给 homebrew 搭建了一个镜像** （因为 homebrew 也就是直接把一个 repo 同步过去而已）。用 Travis-CI 做爬虫也没用超出合理使用范围，一次构建的耗时不过几分钟，而 Travis-CI 对于构建用时是 **完全不限制的**。

事实上我们也无法控制阿里云或者任何一家 VPS 的速度，我认为这个方案的主要缺陷是 HTTPS 和无法实现统计，而不是所谓的“控制”和“独立”。

**Comment by zilongshanren** [comment]
@xuchunyang 
统计是否真的有必要？ 或者我们需要统计信息做什么？用户是否愿意被统计？

**Comment by CodeFalling** [comment]
而且我是将目前的方案作为过渡方案提出的，我支持未来备案后再转 VPS。因为我个人认为统计和HTTPS在未来是必要的。

而作为过渡方案，域名的统一性则是必要的。

**Comment by xuchunyang** [comment]
> 而且我是将目前的方案作为过渡方案提出的，我支持未来备案后再转 VPS。

我以为已经决定不备案了呢。

> 而作为过渡方案，域名的统一性则是必要的。

一直用 elpa.zilongshanren.com 有什么不一致的地方吗？（就算以后换域名，重定向过去也行）

**Comment by CodeFalling** [comment]
我只是觉得使用个人域名看起来比使用商业公司的免费服务看起来奇怪的多（毕竟我们也同时在使用 Github Slack Youtube)

不过如果确定要使用 VPS 的话，让 Travis CI 最后一步的 git push 改成 rsync 上 VPS 或者让 VPS 从 repo 里 Clone 都可以。然后只要起一个静态的 nginx 服务器即可。因为我试了一下我的阿里云连 ping melpa.org 都 ping 不同。

**Comment by xuchunyang** [comment]
> 因为我试了一下我的阿里云连 ping melpa.org 都 ping 不同。

这样的话，就一定要用一台境外的服务器了。可以直接用 emacs-china.org 所在的服务器。

**Comment by zilongshanren** [comment]
@xuchunyang  我觉得用 travis 问题不大，没必要再用一台 VPS，我那一台估计不够用了。。。

**Comment by zilongshanren** [comment]
@xuchunyang 
emacs-china.org的 elpa 镜像搭好了吗？

**Comment by xuchunyang** [comment]
没有，感觉不是一两天的事，要基本能用的话：

- [x] 镜像所需的文件通过 travis-ci 下载并同步至 VPS （ `/var/elpa-packages`）
- [ ] 设置一个新分支，定期在上面 commit，使得 travis-ci 能定期同步
- [ ] 设置一个新的文件夹给 nginx （`/var/elpa-packages` 这个文件夹在同步期间可能不稳定），设置 nginx 托管这个新的文件夹

我还在看 nginx 的新手教程，不确定什么时候能搭好。

**Comment by zilongshanren** [comment]
@xuchunyang 
ok, 慢慢来。

**Comment by xuchunyang** [comment]
文件托管放在 @zilongshanren 的 VPS 上，同步依照 @CodeFalling 的想法用 Travis CI 完成。
